import type { Theme } from "@mui/material";

export const getPremiumToggleStyles = (theme: Theme) => ({
  toggleContainer: {
    position: "relative" as const,
    display: "flex",
    alignItems: "center",
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    backdropFilter: "blur(10px)",
    borderRadius: "9999px",
    padding: "4px",
    cursor: "pointer",
    transition: "all 0.3s cubic-bezier(0.4, 0, 0.2, 1)",
    border: "1px solid rgba(255, 255, 255, 0.15)",
    boxShadow: "0 4px 15px rgba(0, 0, 0, 0.2), inset 0 1px 0 rgba(255, 255, 255, 0.1)",
    "&:hover": {
      backgroundColor: "rgba(255, 255, 255, 0.15)",
      boxShadow: "0 6px 20px rgba(0, 0, 0, 0.25), inset 0 1px 0 rgba(255, 255, 255, 0.15)",
      transform: "scale(1.02)",
    },
    "&:active": {
      transform: "scale(0.98)",
    },
  },
  slider: {
    position: "absolute" as const,
    top: "4px",
    left: "4px",
    width: "calc(50% - 4px)",
    height: "calc(100% - 8px)",
    background: `linear-gradient(135deg, ${theme.palette.primary.main} 0%, ${theme.palette.primary.dark} 100%)`,
    borderRadius: "9999px",
    transition: "transform 0.35s cubic-bezier(0.4, 0, 0.2, 1)",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.3), inset 0 1px 0 rgba(255, 255, 255, 0.2)",
  },
  option: (isActive: boolean) => ({
    position: "relative" as const,
    zIndex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "8px 14px",
    borderRadius: "9999px",
    transition: "all 0.25s ease",
    userSelect: "none" as const,
    color: isActive ? "#fff" : "rgba(255, 255, 255, 0.7)",
    fontWeight: isActive ? 600 : 500,
  }),
  optionText: (isActive: boolean) => ({
    fontSize: "0.75rem",
    fontWeight: isActive ? 600 : 500,
    letterSpacing: "0.02em",
    whiteSpace: "nowrap" as const,
    transition: "all 0.25s ease",
    display: { xs: "none", sm: "block" },
  }),
});

export const getTableHeaderStyles = (theme: Theme, isSmallScreen: boolean) => ({
  topHeader: {
    position: "relative" as const,
    backgroundColor: theme.palette.mode === "dark" ? "#111" : "#000000",
    padding: isSmallScreen ? "12px 16px" : "16px 24px",
    borderBottom: "1px solid rgba(255,255,255,0.1)",
  },
  headerFlexContainer: {
    display: "flex",
    position: "relative" as const,
    alignItems: "center",
    width: "100%",
    justifyContent: "center",
  },
  viewToggleContainer: {
    position: "absolute" as const,
    left: 0,
    top: 0,
    height: "100%",
    display: "flex",
    alignItems: "center",
  },
  iconButton: {
    mr: 1,
    color: "#fff",
    backgroundColor: "transparent",
    "&:hover": {
      backgroundColor: "rgba(255,255,255,0.1)",
    },
  },
  viewModeLabel: {
    mr: 2,
    color: "#fff",
    display: { xs: "none", sm: "block" },
  },
  periodTitleContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    width: "100%",
  },
  periodTitle: {
    fontWeight: 700,
    fontSize: "0.75rem",
    letterSpacing: "0.025em",
    textTransform: "uppercase" as const,
    color: "#fff",
  },
  employeeColumn: {
    padding: isSmallScreen ? "6px 12px" : "8px 12px",
    position: "sticky" as const,
    left: 0,
    top: 0,
    zIndex: 20,
    backgroundColor: theme.palette.mode === "dark" ? "#111" : "#000000",
    color: "#fff",
    minHeight: "32px",
    height: "32px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    whiteSpace: "nowrap" as const,
    fontWeight: 600,
    fontSize: "0.8rem",
    borderRight: "1px solid rgba(255,255,255,0.1)",
    "&:hover": {
      backgroundColor: "#333",
    },
  },
  dayHeader: {
    padding: isSmallScreen ? "6px 12px" : "8px 12px",
    backgroundColor: theme.palette.mode === "dark" ? "#111" : "#000000",
    color: "#fff",
    whiteSpace: "nowrap" as const,
    minHeight: "32px",
    height: "32px",
    cursor: "pointer",
    transition: "background-color 0.2s ease",
    fontWeight: 600,
    fontSize: "0.8rem",
    borderBottom: "none",
    "&:hover": {
      backgroundColor: "#333",
    },
  },
  emptyCell: {
    backgroundColor: theme.palette.mode === "dark" ? "#111" : "#000000",
    color: "#fff",
    minHeight: "32px",
    height: "32px",
  },
  periodSelectorCell: {
    padding: isSmallScreen ? "0 12px" : "0 12px",
    backgroundColor: theme.palette.mode === "dark" ? "#111" : "#000000",
    color: "#fff",
    minHeight: "32px",
    height: "32px",
    width: "100%",
    borderBottom: "none",
    display: "flex",
    alignItems: "center",
    verticalAlign: "middle",
  },
});
