/** Frontend Payment type — mirrors the backend payments table (boleta quincenal) */

export interface PaymentEmployee {
  id: number;
  firstName: string;
  lastName: string;
  email?: string | null;
  avatar?: string | null;
  hourlyRate?: number | null;
  nationalId?: string | null;
}

export type PaymentStatus = "pending" | "sent" | "cancelled";

export interface Payment {
  id: number;
  employeeId: number;
  payPeriod: "biweekly";
  biweekNumber: number;
  year: number;
  payDate?: string | null;
  currency: string;
  regularSalary: number;
  overtimePay: number;
  mileage: number;
  others: number;
  socialCharges: number;
  deductions: number;
  totalPayable: number;
  notes?: string | null;
  status: PaymentStatus;
  emailSentAt?: string | null;
  isManual: boolean;
  /** Amount fields typed by hand (kept by automatic refreshes). */
  manualFields: PaymentAmountField[];
  autoGenerated?: boolean;
  hoursWorked?: number | null;
  overtimeHours?: number | null;
  hourlyRate?: number | null;
  /** Current payroll rules (server-side), for live previews while editing. */
  socialChargesRate?: number;
  overtimeMultiplier?: number;
  createdAt?: string;
  updatedAt?: string;
  employee?: PaymentEmployee;
}

/** Editable amount fields of a payment (total is always recomputed server-side). */
export type PaymentAmountField =
  | "regularSalary"
  | "overtimePay"
  | "mileage"
  | "others"
  | "socialCharges"
  | "deductions";

export interface PaymentAmounts {
  regularSalary: number;
  overtimePay: number;
  mileage: number;
  others: number;
  socialCharges: number;
  deductions: number;
}

/** Server-side breakdown preview (GET /payments/recalculate/...). */
export interface PaymentBreakdown extends PaymentAmounts {
  employeeId: number;
  biweekNumber: number;
  year: number;
  startDate: string;
  endDate: string;
  hoursWorked: number;
  regularHours: number;
  overtimeHours: number;
  hourlyRate: number | null;
  socialChargesRate: number;
  overtimeMultiplier: number;
  totalPayable: number;
  manualFields: PaymentAmountField[];
}

/** Concepts of the "Comprobante de pago", in the template's order. */
export const PAYMENT_CONCEPTS: ReadonlyArray<{
  field: PaymentAmountField;
  label: string;
  kind: "earning" | "deduction";
}> = [
  { field: "regularSalary", label: "Salario ordinario", kind: "earning" },
  { field: "overtimePay", label: "Salario extraordinario", kind: "earning" },
  { field: "mileage", label: "Kilometraje", kind: "earning" },
  { field: "others", label: "Otros", kind: "earning" },
  { field: "socialCharges", label: "Cargas Sociales", kind: "deduction" },
  { field: "deductions", label: "Rebajos", kind: "deduction" },
];

/** Result of POST /payments/generate. */
export interface PaymentGenerationResult {
  year: number;
  biweekNumber: number;
  created: number;
  refreshed: number;
  skipped: number;
}
