const BRANDS_LIST = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Buick", label: "Buick" },
  { value: "BYD", label: "BYD" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Changan", label: "Changan" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chery", label: "Chery" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroën", label: "Citroën" },
  { value: "Dodge", label: "Dodge" },
  { value: "Dongfeng", label: "Dongfeng" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "Foton", label: "Foton" },
  { value: "Geely", label: "Geely" },
  { value: "GMC", label: "GMC" },
  { value: "Great Wall", label: "Great Wall" },
  { value: "Haval", label: "Haval" },
  { value: "Honda", label: "Honda" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "Jac", label: "Jac" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Lucid", label: "Lucid" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MG", label: "MG" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Pagani", label: "Pagani" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Ram", label: "Ram" },
  { value: "Renault", label: "Renault" },
  { value: "Rivian", label: "Rivian" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Saab", label: "Saab" },
  { value: "Seat", label: "Seat" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
  { value: "Wuling", label: "Wuling" },
  { value: "Xpeng", label: "Xpeng" },
];
export default BRANDS_LIST;
