const FORMS = {
  ALREADY_REGISTERED: "Ya está registrado",
  DAYS_REQUIRED: "Debe seleccionar al menos un día",
  DISTANCE_GREATER_0: "La distancia debe ser mayor a 0",
  DISTANCE_MAX_1000: "La distancia no puede ser mayor a 1000 km",
  EMAIL_EXISTS: "El correo electrónico ya existe",
  EMAIL_FORMAT: "El correo electrónico no tiene un formato válido",
  EMAIL_INVALID: "El correo electrónico no tiene un formato válido",
  EMAIL_REQUIRED: "El correo electrónico es requerido",
  FIRST_NAME: "Nombre",
  FIRST_NAME_REQUIRED: "El nombre es requerido",
  HOURS_INVALID: "Las horas deben ser un número entre 1 y 24",
  HOURS_REQUIRED: "Las horas son requeridas",
  INVALID_FORMAT_EXAMPLE: "Formato inválido. Ejemplo: 123ABC",
  INVALID_FORMAT_PARKING: "Formato inválido. Ejemplo: ATP1-123",
  LABEL_REQUIRED: "Etiqueta requerida",
  LAST_NAME: "Apellido",
  LAST_NAME_REQUIRED: "El apellido es requerido",
  LETTERS_SPACES_HYPHENS: "Solo se permiten letras, espacios y guiones",
  LICENSE_PLATE_ALREADY_REGISTERED: "La placa ya está registrada",
  LOGIN_DESCRIPTION: "Ingresa tus credenciales para acceder al sistema",
  MAX_100_CHARS: "No puede tener más de 100 caracteres",
  MAX_30_CHARS: "No puede tener más de 30 caracteres",
  MAX_50_CHARS: "No puede tener más de 50 caracteres",
  MIN_2_CHARS: "Debe tener al menos 2 caracteres",
  MIN_3_CHARS: "Debe tener al menos 3 caracteres",
  NAME_LETTERS_ONLY: "Solo se permiten letras, espacios y guiones",
  PASSWORD_COMPLEXITY:
    "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_INVALID:
    "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_REQUIRED: "La contraseña es requerida",
  PASSWORDS_DONT_MATCH: "Las contraseñas no coinciden",
  PASSWORDS_REQUIRED: "Ambas contraseñas son requeridas",
  POSITIVE_NUMBER_ONLY: "Solo se permiten números positivos",
  REQUIRED_FIELD: "Este campo es requerido",
  ROLE_REQUIRED: "El rol es requerido",
  TRACKING_MAX_50: "No puede tener más de 50 caracteres",
  TRACKING_MIN_3: "Debe tener al menos 3 caracteres",
  USERNAME_EXISTS: "El nombre de usuario ya existe",
  USERNAME_FORMAT:
    "El usuario debe comenzar con una letra y tener entre 3 y 20 caracteres",
  USERNAME_INVALID:
    "El usuario debe comenzar con una letra y tener 3-20 caracteres",
  USERNAME_REQUIRED: "El usuario es requerido",
  USERNAME_START_LETTER: "El usuario debe comenzar con una letra",
  ADD_USER: {
    INFO_TITLE: "Información del Usuario",
    INFO_DESC:
      "Guía para crear un nuevo usuario con acceso al sistema. La contraseña debe cumplir con los requisitos de seguridad.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Ej: juan.perez@empresa.com",
    USERNAME_LABEL: "Nombre de Usuario",
    USERNAME_PLACEHOLDER: "Ej: juan.perez",
    PASSWORD_LABEL: "Contraseña",
    PASSWORD_PLACEHOLDER: "Mínimo 8 caracteres",
    ROLE_LABEL: "Rol",
    BUTTON_ADD: "Crear",
    BUTTON_ADDING: "Creando...",
  },
  ADD_EMPLOYEE: {
    INFO_TITLE: "Información del Empleado",
    INFO_DESC:
      "Guía para registrar los datos personales del empleado. Solo se permiten letras, espacios y guiones.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    EMAIL_LABEL: "Correo Electrónico",
    EMAIL_PLACEHOLDER: "Ej: juan.perez@empresa.com",
    NATIONAL_ID_LABEL: "Cédula",
    NATIONAL_ID_PLACEHOLDER: "Ej: 1-2345-6789",
    PRIMARY_PHONE_LABEL: "Teléfono principal",
    PRIMARY_PHONE_PLACEHOLDER: "Ej: 8312-3456",
    SECONDARY_PHONE_LABEL: "Teléfono secundario",
    SECONDARY_PHONE_PLACEHOLDER: "Ej: 8312-3456",
    POSITION_LABEL: "Puesto",
    POSITION_PLACEHOLDER: "Selecciona",
    GENDER_LABEL: "Género",
    GENDER_PLACEHOLDER: "Selecciona",
    CONTRACT_START_DATE_LABEL: "Fecha de contrato",
    CONTRACT_START_DATE_PLACEHOLDER: "YYYY-MM-DD",
    HOURLY_RATE_LABEL: "Tarifa por hora",
    HOURLY_RATE_PLACEHOLDER: "Ej: 2500.00",
    VACATION_DAYS_LABEL: "Días de vacaciones",
    VACATION_DAYS_PLACEHOLDER: "Ej: 12",
    BUTTON_ADD: "Crear",
    BUTTON_ADDING: "Creando...",
  },
  ADD_ROLE: {
    INFO_TITLE: "Información del Rol",
    INFO_DESC:
      "Define el nombre y permisos del rol. Los permisos determinan las acciones disponibles para los usuarios.",
    NAME_LABEL: "Nombre del Rol",
    NAME_PLACEHOLDER: "Ej: Administrador",
    PERMISSIONS_LABEL: "Permisos del Rol",
    PERMISSIONS_SELECTED: (count: number) =>
      `Permisos Seleccionados (${count})`,
    BUTTON_ADD: "Crear",
    BUTTON_ADDING: "Creando...",
  },
  ADD_VEHICLE: {
    INFO_TITLE: "Información del Vehículo",
    INFO_DESC:
      "Guía para registrar los datos del vehículo. La boleta y placa deben ser únicas en el sistema.",
    TICKET_LABEL: "Boleta",
    TICKET_PLACEHOLDER: "Ej: 12345",
    LICENSE_PLATE_LABEL: "Placa",
    LICENSE_PLATE_PLACEHOLDER: "Ej: ABC-123",
    BRAND_LABEL: "Marca",
    COLOR_LABEL: "Color",
    PARKING_LOT_LABEL: "Espacio de Parqueo",
    PARKING_LOT_PLACEHOLDER: "Ej: ATP1-123",
    PARKING_DATE_LABEL: "Fecha de Parqueo",
    OBSERVATIONS_LABEL: "Observaciones",
    OBSERVATIONS_PLACEHOLDER: "Observaciones adicionales sobre el vehículo...",
    BUTTON_ADD: "Crear",
    BUTTON_ADDING: "Creando...",
    NO_OPTIONS: "Sin coincidencias",
  },
  ADD_SCHEDULE: {
    INFO_TITLE: "Información del Horario",
    INFO_DESC:
      "Guía para configurar el horario y lugar de trabajo. Marca la opción especial si aplica.",
    SCHEDULE_LABEL: "Horario/Lugar",
    SCHEDULE_LABEL_PLACEHOLDER: "Ej: Avenida 123",
    SCHEDULE_TIME_LABEL: "Tiempo",
    SCHEDULE_TIME_PLACEHOLDER: "Ej: 8 horas",
    BUTTON_ADD: "Crear",
    BUTTON_ADDING: "Creando...",
  },
};

export const PASSWORD_INFO_TITLE = "Información de la contraseña";
export const PASSWORD_INFO_DESC = "La contraseña debe tener al menos 8 caracteres, incluir mayúsculas, minúsculas, un número y un carácter especial. Por seguridad, no compartas tu contraseña con nadie. Puedes generar una contraseña temporal para el usuario si es necesario.";

export default FORMS;
