export const ROUTES = {
  // Routes
  COURIER_SERVICE: "/courier-service",
  DASHBOARD: "/dashboard",
  EMPLOYEES: "/employees",
  LOGIN: "/",
  REGISTER: "register",
  ROLES: "/roles",
  SCHEDULES: "/schedules",
  SETTINGS: "/settings",
  VEHICLES: "/vehicles",
};

export const APPBAR_MENU = {
  // Menu items
  COURIER_SERVICE: "Mensajería",
  DASHBOARD: "Administración",
  EMPLOYEES: "Empleados",
  LOGOUT: "Cerrar Sesión",
  MANAGE: "Gestión",
  ROLES: "Roles",
  SCHEDULES: "Horarios",
  SETTINGS: "Configuración",
  TITLE: "Choferes de Alquiler",
  TITLE_SIMPLIFIED: "Choferes",
  VEHICLES: "Vehículos",
  NO_LINKS: "No hay links disponibles",
  NOTIFICATIONS: "Notificaciones",
  USER_MENU: "Menú de Usuario",
};

export const PAGE_TITLE = {
  // Page titles
  COURIER_SERVICE: "Servicio de Mensajería",
  COURIER_SERVICE_SIMPLIFIED: "Mensajería",
  DASHBOARD: "Panel de Control Administrativo",
  DASHBOARD_SIMPLIFIED: "Administración",
  EMPLOYEES: "Gestión de Personal",
  EMPLOYEES_SIMPLIFIED: "Empleados",
  LOGIN: "Iniciar Sesión",
  REGISTER: "Crear Cuenta",
  ROLES: "Gestión de Roles",
  ROLES_SIMPLIFIED: "Roles",
  SCHEDULES: "Gestión de Horarios",
  SCHEDULES_SIMPLIFIED: "Horarios",
  SETTINGS: "Configuración del Sistema",
  VEHICLES: "Gestión de Vehículos",
  VEHICLES_SIMPLIFIED: "Vehículos",
};

export const PERMISSIONS = {
  // Permissions
  CREATE_EMPLOYEES: "Crear Empleado",
  CREATE_ROLE: "Crear Rol",
  CREATE_SCHEDULES: "Crear Horario",
  CREATE_VEHICLES: "Crear Vehículo",
  DELETE_EMPLOYEES: "Eliminar Empleado",
  DELETE_ROLE: "Eliminar Rol",
  DELETE_SCHEDULES: "Eliminar Horario",
  DELETE_VEHICLES: "Eliminar Vehículo",
  EDIT_EMPLOYEE_ROLES: "Editar Roles de Empleados",
  EDIT_EMPLOYEES: "Editar Empleado",
  EDIT_ROLE: "Editar Rol",
  EDIT_SCHEDULES: "Editar Horario",
  EDIT_USER: "Editar Usuario",
  EDIT_VEHICLES: "Editar Vehículo",
  ENABLE_DISABLE_USER: "Habilitar/Deshabilitar Usuario",
  EXPORT_EXCEL_EMPLOYEES: "Exportar Excel de Empleados",
  EXPORT_EXCEL_ROLES: "Exportar Excel de Roles de Empleados",
  EXPORT_EXCEL_SCHEDULES: "Exportar Excel de Horarios",
  EXPORT_EXCEL_VEHICLES: "Exportar Excel de Vehículos",
  EXPORT_PDF_EMPLOYEES: "Exportar PDF de Empleados",
  EXPORT_PDF_ROLES: "Exportar PDF de Roles de Empleados",
  EXPORT_PDF_SCHEDULES: "Exportar PDF de Horarios",
  EXPORT_PDF_VEHICLES: "Exportar PDF de Vehículos",
  VIEW_ADMIN: "Ver Admin",
  VIEW_COURIER_SERVICE: "Ver Mensajería",
  VIEW_EMPLOYEE_ROLES_HOURS: "Ver Horas de Empleados",
  VIEW_EMPLOYEES: "Ver Empleados",
  VIEW_ROLES: "Ver Roles",
  VIEW_SCHEDULES: "Ver Horarios",
  VIEW_VEHICLES: "Ver Vehículos",
};

export const DAYS_LIST = [
  // Weekdays
  { value: "monday", label: "Lunes" },
  { value: "tuesday", label: "Martes" },
  { value: "wednesday", label: "Miércoles" },
  { value: "thursday", label: "Jueves" },
  { value: "friday", label: "Viernes" },
  { value: "saturday", label: "Sábado" },
  { value: "sunday", label: "Domingo" },
];

export const OVERTIME = {
  // Overtime limits
  BIWEEKLY: 96,
  MONTHLY: 192,
  WEEKLY: 48,
};

export const COLORS_LIST = [
  // Vehicle colors
  { value: "Blanco", label: "Blanco" },
  { value: "Negro", label: "Negro" },
  { value: "Gris", label: "Gris" },
  { value: "Azul", label: "Azul" },
  { value: "Rojo", label: "Rojo" },
  { value: "Verde", label: "Verde" },
  { value: "Amarillo", label: "Amarillo" },
  { value: "Naranja", label: "Naranja" },
  { value: "Café", label: "Café" },
  { value: "Plateado", label: "Plateado" },
  { value: "Dorado", label: "Dorado" },
  { value: "Vino", label: "Vino" },
  { value: "Beige", label: "Beige" },
  { value: "Morado", label: "Morado" },
  { value: "Turquesa", label: "Turquesa" },
  { value: "Púrpura", label: "Púrpura" },
  { value: "Celeste", label: "Celeste" },
  { value: "Bronce", label: "Bronce" },
  { value: "Champán", label: "Champán" },
];

export const BRANDS_LIST = [
  // Vehicle brands
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Buick", label: "Buick" },
  { value: "BYD", label: "BYD" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Changan", label: "Changan" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chery", label: "Chery" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroën", label: "Citroën" },
  { value: "Dodge", label: "Dodge" },
  { value: "Dongfeng", label: "Dongfeng" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "Foton", label: "Foton" },
  { value: "Geely", label: "Geely" },
  { value: "GMC", label: "GMC" },
  { value: "Great Wall", label: "Great Wall" },
  { value: "Haval", label: "Haval" },
  { value: "Honda", label: "Honda" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "Jac", label: "Jac" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Lucid", label: "Lucid" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MG", label: "MG" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Pagani", label: "Pagani" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Ram", label: "Ram" },
  { value: "Renault", label: "Renault" },
  { value: "Rivian", label: "Rivian" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Saab", label: "Saab" },
  { value: "Seat", label: "Seat" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
  { value: "Wuling", label: "Wuling" },
  { value: "Xpeng", label: "Xpeng" },
];

export const STATE = {
  // States
  FREE: "Libre",
};

// TABLE: Table-related labels and tooltips for UI tables
export const TABLE = {
  EDIT: "Editar",
  SAVE: "Guardar",
  CANCEL: "Cancelar",
  DELETE: "Eliminar",
  ACTIONS: "Acciones",
  NO_DATA: "No hay registros para mostrar",
  LOADING: "Cargando...",
  ROWS_PER_PAGE: "Filas por página",
  PAGE: "Página",
  OF: "de",
  PERMISSIONS_LABEL: "Permisos:",
  MORE: "+{n} más",
  SEARCH_PLACEHOLDER: "Buscar...",
  CONFIRM_DELETE_TITLE: "¿Eliminar registro?",
  CONFIRM_DELETE_TEXT: "¿Estás seguro de que deseas eliminar este registro? Esta acción no se puede deshacer.",
  CONFIRM_DELETE_ACCEPT: "Sí, eliminar",
  CONFIRM_DELETE_CANCEL: "Cancelar",
  TOOLTIP_EDIT: "Editar",
  TOOLTIP_DELETE: "Eliminar",
  TOOLTIP_SAVE: "Guardar cambios",
  TOOLTIP_CANCEL: "Cancelar edición",
  TOOLTIP_PASSWORD: "Cambiar contraseña",
  TOOLTIP_STATUS: "Activar/Desactivar",
  ENABLE: "Activar",
  DISABLE: "Desactivar",
  CHANGE_PASSWORD: "Cambiar contraseña",
};

// SELECTOR_TABLE: Labels and tooltips for the SelectorTable component
export const SELECTOR_TABLE = {
  PERIOD_WEEKLY: "Semanal",
  PERIOD_BIWEEKLY: "Quincenal",
  PERIOD_MONTHLY: "Mensual",
  WEEKLY: "Semanal",
  BIWEEKLY: "Quincenal",
  MONTHLY: "Mensual",
  WEEKS: "Semanas",
  WEEK: "Semana",
  BIWEEKS: "Quincenas",
  BIWEEK: "Quincena",
  EMPLOYEES: "Empleados",
  LOCATIONS: "Ubicaciones",
  SPECIAL_SCHEDULES: "Horarios Especiales",
  OTHER: "Otro",
  TOTAL_HOURS: "Horas totales",
  OVERTIME: "Horas extra",
  OVERTIME_HOURS: "Horas Extra",
  NO_EMPLOYEES: "No hay empleados para mostrar",
  ADJUST_TIME: "Ajustar tiempo",
  INFO: "Información",
  CLOSE: "Cerrar",
  ADJUST: "Ajustar",
  ADJUST_HOURS: "Ajuste de Horas",
  HOURS: "Horas",
  MINUTES: "Minutos",
  SEARCH_EMPLOYEE: "Buscar empleado...",
  SELECT_PERIOD: "Seleccionar periodo",
  TOOLTIP_INFO: "Ver información del empleado",
  TOOLTIP_ADJUST: "Ajustar horas trabajadas",
  WEEKLY_HOURS_MESSAGE: "Total de horas trabajadas en la semana:",
  BIWEEKLY_HOURS_MESSAGE: "Total de horas trabajadas en la quincena:",
  MONTHLY_HOURS_MESSAGE: "Total de horas trabajadas en el mes:",
  HOURS_TO_ADJUST: "Horas a ajustar",
  POSITIVE_NUMBER_REQUIRED: "Debe ser un número positivo",
  ADJUSTMENT_INFO: "Información de Ajuste",
  ADJUSTMENT_DESCRIPTION: "Ingresa la cantidad de horas a sumar o restar. Solo se permiten valores positivos.",
  CANCEL: "Cancelar",
  ADD: "Sumar",
  SUBTRACT: "Restar",
};

export const FORMS = {
  // General validations and labels
  ALREADY_REGISTERED: "Ya está registrado",
  DAYS_REQUIRED: "Debe seleccionar al menos un día",
  DISTANCE_GREATER_0: "La distancia debe ser mayor a 0",
  DISTANCE_MAX_1000: "La distancia no puede ser mayor a 1000 km",
  EMAIL_EXISTS: "El correo electrónico ya existe",
  EMAIL_FORMAT: "El correo electrónico no tiene un formato válido",
  EMAIL_INVALID: "El correo electrónico no tiene un formato válido",
  EMAIL_REQUIRED: "El correo electrónico es requerido",
  FIRST_NAME: "Nombre",
  FIRST_NAME_REQUIRED: "El nombre es requerido",
  HOURS_INVALID: "Las horas deben ser un número entre 1 y 24",
  HOURS_REQUIRED: "Las horas son requeridas",
  INVALID_FORMAT_EXAMPLE: "Formato inválido. Ejemplo: 123ABC",
  INVALID_FORMAT_PARKING: "Formato inválido. Ejemplo: A-12",
  LABEL_REQUIRED: "Etiqueta requerida",
  LAST_NAME: "Apellido",
  LAST_NAME_REQUIRED: "El apellido es requerido",
  LETTERS_SPACES_HYPHENS: "Solo se permiten letras, espacios y guiones",
  LICENSE_PLATE_ALREADY_REGISTERED: "La placa ya está registrada",
  LOGIN_DESCRIPTION: "Ingresa tus credenciales para acceder al sistema",
  MAX_100_CHARS: "No puede tener más de 100 caracteres",
  MAX_30_CHARS: "No puede tener más de 30 caracteres",
  MAX_50_CHARS: "No puede tener más de 50 caracteres",
  MIN_2_CHARS: "Debe tener al menos 2 caracteres",
  MIN_3_CHARS: "Debe tener al menos 3 caracteres",
  NAME_LETTERS_ONLY: "Solo se permiten letras, espacios y guiones",
  PASSWORD_COMPLEXITY: "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_INVALID: "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_REQUIRED: "La contraseña es requerida",
  PASSWORDS_DONT_MATCH: "Las contraseñas no coinciden",
  PASSWORDS_REQUIRED: "Ambas contraseñas son requeridas",
  POSITIVE_NUMBER_ONLY: "Solo se permiten números positivos",
  REQUIRED_FIELD: "Este campo es requerido",
  ROLE_REQUIRED: "El rol es requerido",
  TRACKING_MAX_50: "No puede tener más de 50 caracteres",
  TRACKING_MIN_3: "Debe tener al menos 3 caracteres",
  USERNAME_EXISTS: "El nombre de usuario ya existe",
  USERNAME_FORMAT: "El usuario debe comenzar con una letra y tener entre 3 y 20 caracteres",
  USERNAME_INVALID: "El usuario debe comenzar con una letra y tener 3-20 caracteres",
  USERNAME_REQUIRED: "El usuario es requerido",
  USERNAME_START_LETTER: "El usuario debe comenzar con una letra",
  ADD_USER: {
    INFO_TITLE: "Información del Usuario",
    INFO_DESC: "Completa todos los campos para crear un nuevo usuario. La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Ej: juan.perez@empresa.com",
    USERNAME_LABEL: "Nombre de Usuario",
    USERNAME_PLACEHOLDER: "Ej: juan.perez",
    PASSWORD_LABEL: "Contraseña",
    PASSWORD_PLACEHOLDER: "Mínimo 8 caracteres",
    ROLE_LABEL: "Rol",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_EMPLOYEE: {
    INFO_TITLE: "Información del Empleado",
    INFO_DESC: "Ingresa el nombre completo del empleado. Solo se permiten letras, espacios y guiones.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_ROLE: {
    INFO_TITLE: "Información del Rol",
    INFO_DESC: "Define el nombre y permisos del nuevo rol. Los permisos determinan qué acciones puede realizar un usuario con este rol en el sistema.",
    NAME_LABEL: "Nombre del Rol",
    NAME_PLACEHOLDER: "Ej: Administrador",
    PERMISSIONS_LABEL: "Permisos del Rol",
    PERMISSIONS_SELECTED: (count: number) => `Permisos Seleccionados (${count})`,
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_VEHICLE: {
    INFO_TITLE: "Información Importante",
    INFO_DESC: "Completa todos los campos requeridos. La boleta y placa deben ser únicas.",
    INFO_OPTIONAL: 'Puedes usar "N/A" para campos opcionales.',
    TICKET_LABEL: "Boleta",
    TICKET_PLACEHOLDER: "Ej: 12345",
    LICENSE_PLATE_LABEL: "Placa",
    LICENSE_PLATE_PLACEHOLDER: "Ej: ABC-123",
    BRAND_LABEL: "Marca",
    COLOR_LABEL: "Color",
    PARKING_LOT_LABEL: "Espacio de Parqueo",
    PARKING_LOT_PLACEHOLDER: "Ej: ATP1-123",
    PARKING_DATE_LABEL: "Fecha de Parqueo",
    OBSERVATIONS_LABEL: "Observaciones",
    OBSERVATIONS_PLACEHOLDER: "Observaciones adicionales sobre el vehículo...",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
    NO_OPTIONS: "Sin coincidencias",
  },
  ADD_COURIER: {
    INFO_TITLE: "Información del Servicio de Mensajería",
    INFO_DESC: "Completa todos los campos requeridos para registrar un nuevo servicio de mensajería.",
    DRIVER: "Chofer",
    DRIVER_PLACEHOLDER: "Ej: Juan Pérez",
    ROUTE: "Ruta",
    DISTANCE: "Distancia (km)",
    DISTANCE_PLACEHOLDER: "Ej: 45",
    TRACKING_NUMBER: "Número de Guía",
    TRACKING_NUMBER_PLACEHOLDER: "Ej: TRK001",
    STATUS: "Estado",
    STATUS_DESPACHADO: "Despachado",
    STATUS_EN_TRANSITO: "En Tránsito",
    STATUS_ENTREGADO: "Entregado",
    CLEAR_BUTTON: "Limpiar",
    CANCEL_BUTTON: "Cancelar",
    LOADING_BUTTON: "Agregando...",
    ADD_BUTTON: "Agregar",
  },
  ADD_SCHEDULE: {
    SPECIAL_LABEL: "Horario Especial",
    SPECIAL_DESC: "Marque esta opción si es un horario con condiciones especiales",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
};

export const NOTIFICATIONS = {
  // Success messages
  USER_CREATED: "Usuario creado exitosamente",
  USER_UPDATED: "Usuario actualizado exitosamente",
  USER_DELETED: "Usuario eliminado exitosamente",
  EMPLOYEE_CREATED: "El registro del empleado fue exitoso",
  EMPLOYEE_UPDATED: "La actualización del empleado fue exitosa",
  EMPLOYEE_DELETED: "Empleado eliminado exitosamente",
  SCHEDULE_CREATED: "El registro del horario fue exitoso",
  SCHEDULE_UPDATED: "La actualización del horario fue exitosa",
  SCHEDULE_DELETED: "Horario eliminado exitosamente",
  VEHICLE_CREATED: "El registro del vehículo fue exitoso",
  VEHICLE_UPDATED: "La actualización del vehículo fue exitosa",
  VEHICLE_DELETED: "Vehículo eliminado exitosamente",
  ROLE_CREATED: "El registro del rol fue exitoso",
  ROLE_UPDATED: "La actualización del rol fue exitosa",
  ROLE_DELETED: "Rol eliminado exitosamente",
  USER_REGISTERED: "El registro del usuario fue exitoso",
  DATA_UPDATED: "La actualización de lo datos fue exitosa",
  PASSWORD_UPDATED: "La actualización de la contraseña fue exitosa",
  
  // Error messages
  USER_CREATE_ERROR: "Error al crear el usuario",
  USER_UPDATE_ERROR: "Error al actualizar el usuario",
  USER_DELETE_ERROR: "Error al eliminar el usuario",
  EMPLOYEE_CREATE_ERROR: "Ha ocurrido un error al registrar el empleado",
  EMPLOYEE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el empleado",
  EMPLOYEE_DELETE_ERROR: "Error al eliminar el empleado",
  SCHEDULE_CREATE_ERROR: "Ha ocurrido un error al registrar el horario",
  SCHEDULE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el horario",
  SCHEDULE_DELETE_ERROR: "Error al eliminar el horario",
  VEHICLE_CREATE_ERROR: "Ha ocurrido un error al registrar el vehículo",
  VEHICLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el vehículo",
  VEHICLE_DELETE_ERROR: "Error al eliminar el vehículo",
  ROLE_CREATE_ERROR: "Ha ocurrido un error al registrar el rol",
  ROLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el rol",
  ROLE_DELETE_ERROR: "Error al eliminar el rol",
  USER_REGISTER_ERROR: "Error al registrar usuario",
  USER_REGISTER_ERROR_DETAIL: "Ha ocurrido un error al registrar el usuario",
  DATA_UPDATE_ERROR: "Ha ocurrido un error al actualizar los datos",
  PASSWORD_UPDATE_ERROR: "Ha ocurrido un error al actualizar la contraseña",
  ROLE_NOT_FOUND: "Rol no encontrado",
  RETRY_MESSAGE: "Intenta de nuevo",
  EMPLOYEE_CREATE_SUCCESS: "El registro del empleado fue exitoso",
  EMPLOYEE_UPDATE_SUCCESS: "La actualización del empleado fue exitosa",
  EMPLOYEE_DELETE_SUCCESS: "Empleado eliminado exitosamente",
  SCHEDULE_CREATE_SUCCESS: "El registro del horario fue exitoso",
  SCHEDULE_UPDATE_SUCCESS: "La actualización del horario fue exitosa",
  SCHEDULE_DELETE_SUCCESS: "Horario eliminado exitosamente",
  VEHICLE_CREATE_SUCCESS: "Vehículo creado exitosamente",
  VEHICLE_DELETE_SUCCESS: "Vehículo eliminado exitosamente",
  COURIER_CREATE_SUCCESS: "Servicio de mensajería creado exitosamente",
  COURIER_UPDATE_SUCCESS: "La actualización del servicio fue exitosa",
  COURIER_DELETE_SUCCESS: "Servicio de mensajería eliminado exitosamente",
  COURIER_UPDATE_ERROR: "Ha ocurrido un error al actualizar el servicio de mensajería",
  COURIER_DELETE_ERROR: "Ha ocurrido un error al eliminar el servicio de mensajería",
  ROLE_CREATE_SUCCESS: "Rol creado exitosamente",
  ROLE_UPDATE_SUCCESS: "La actualización del rol fue exitosa",
  ROLE_DELETE_SUCCESS: "Rol eliminado exitosamente",
  USER_CREATE_SUCCESS: "Usuario creado exitosamente",
  USER_UPDATE_SUCCESS: "La actualización del usuario fue exitosa",
  USER_ROLE_NOT_FOUND: "El rol seleccionado no existe",
  USER_STATUS_UPDATE_SUCCESS: "Estado del usuario actualizado exitosamente",
  USER_STATUS_UPDATE_ERROR: "Error al actualizar el estado del usuario",
  USER_PASSWORD_UPDATE_SUCCESS: "La contraseña fue actualizada exitosamente",
  USER_PASSWORD_UPDATE_ERROR: "Ha ocurrido un error al actualizar la contraseña",
  COURIER_CREATE_ERROR: "Ha ocurrido un error al crear el servicio de mensajería",
};

export const AUTH = {
  EMAIL_OR_USERNAME: "Correo Electrónico o Usuario",
  EMAIL_OR_USERNAME_REQUIRED: "El correo electrónico o usuario es requerido",
  PASSWORD: "Contraseña",
  LOGIN: "Iniciar Sesión",
  LOGGING_IN: "Iniciando Sesión...",
  PERSONAL_INFO: "Información Personal",
  PERSONAL_INFO_DESCRIPTION: "Actualiza tu información personal y credenciales de acceso",
  FIRST_NAME: "Nombre",
  LAST_NAME: "Apellido",
  EMAIL: "Correo electrónico",
  USERNAME: "Usuario",
  UPDATE_PERSONAL_INFO: "Actualizar Información Personal",
  UPDATING_PERSONAL_INFO: "Actualizando...",
  PERSONAL_INFO_SUCCESS: "La actualización de lo datos fue exitosa",
  PERSONAL_INFO_ERROR: "Ha ocurrido un error al actualizar los datos",
  CHANGE_PASSWORD: "Cambiar Contraseña",
  CHANGE_PASSWORD_DESCRIPTION: "Actualiza tu contraseña para mantener tu cuenta segura",
  NEW_PASSWORD: "Nueva contraseña",
  CONFIRM_NEW_PASSWORD: "Confirmar nueva contraseña",
  UPDATE_PASSWORD: "Actualizar Contraseña",
  UPDATING_PASSWORD: "Actualizando...",
  PASSWORD_SUCCESS: "La actualización de la contraseña fue exitosa",
  PASSWORD_ERROR: "Ha ocurrido un error al actualizar la contraseña",
  SHOW_PASSWORD: "Mostrar contraseña",
  HIDE_PASSWORD: "Ocultar contraseña",
  REGISTER_DESCRIPTION: "Completa el formulario para crear una cuenta",
  REGISTER_SUCCESS: "El registro del usuario fue exitoso",
  REGISTER_ERROR: "Error al registrar usuario",
};

export const MANAGEMENT = {
  // Common actions
  ADD: "Agregar",
  EDIT: "Editar",
  DELETE: "Eliminar",
  CANCEL: "Cancelar",
  SEARCH: "Buscar",
  EXPORT: "Exportar",
  
  // Success messages
  CREATE_SUCCESS: "El registro fue exitoso",
  UPDATE_SUCCESS: "La actualización fue exitosa",
  DELETE_SUCCESS: "Elemento eliminado exitosamente",
  
  // Error messages
  CREATE_ERROR: "Ha ocurrido un error al registrar",
  UPDATE_ERROR: "Ha ocurrido un error al actualizar",
  DELETE_ERROR: "Error al eliminar",
  
  // Employees
  EMPLOYEES: "Empleados",
  EMPLOYEE: "Empleado",
  NEW_EMPLOYEE: "Nuevo empleado",
  SEARCH_EMPLOYEE: "Buscar empleado",
  DELETE_EMPLOYEE: "Eliminar Empleado",
  EMPLOYEE_CREATE_SUCCESS: "El registro del empleado fue exitoso",
  EMPLOYEE_CREATE_ERROR: "Ha ocurrido un error al registrar el empleado",
  EMPLOYEE_UPDATE_SUCCESS: "La actualización del empleado fue exitosa",
  EMPLOYEE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el empleado",
  EMPLOYEE_DELETE_SUCCESS: "Empleado eliminado exitosamente",
  EMPLOYEE_DELETE_ERROR: "Error al eliminar el empleado",
  
  // Schedules
  SCHEDULES: "Horarios",
  SCHEDULE: "Horario",
  NEW_SCHEDULE: "Nuevo horario",
  SEARCH_SCHEDULE: "Buscar horario",
  DELETE_SCHEDULE: "Eliminar Horario",
  SCHEDULE_CREATE_SUCCESS: "El registro del horario fue exitoso",
  SCHEDULE_CREATE_ERROR: "Ha ocurrido un error al registrar el horario",
  SCHEDULE_UPDATE_SUCCESS: "La actualización del horario fue exitosa",
  SCHEDULE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el horario",
  SCHEDULE_DELETE_SUCCESS: "Horario eliminado exitosamente",
  SCHEDULE_DELETE_ERROR: "Error al eliminar el horario",
  
  // Vehicles
  VEHICLES: "Vehículos",
  VEHICLE: "Vehículo",
  NEW_VEHICLE: "Nuevo vehículo",
  SEARCH_VEHICLE: "Buscar vehículo",
  DELETE_VEHICLE: "Eliminar Vehículo",
  VEHICLE_CREATE_SUCCESS: "El registro del vehículo fue exitoso",
  VEHICLE_CREATE_ERROR: "Ha ocurrido un error al registrar el vehículo",
  VEHICLE_UPDATE_SUCCESS: "La actualización del vehículo fue exitosa",
  VEHICLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el vehículo",
  VEHICLE_DELETE_SUCCESS: "Vehículo eliminado exitosamente",
  VEHICLE_DELETE_ERROR: "Error al eliminar el vehículo",
  
  // Roles
  ROLES: "Roles",
  ROLE: "Rol",
  NEW_ROLE: "Nuevo rol",
  SEARCH_ROLE: "Buscar rol",
  DELETE_ROLE: "Eliminar Rol",
  ROLE_CREATE_SUCCESS: "El registro del rol fue exitoso",
  ROLE_CREATE_ERROR: "Ha ocurrido un error al registrar el rol",
  ROLE_UPDATE_SUCCESS: "La actualización del rol fue exitosa",
  ROLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el rol",
  ROLE_DELETE_SUCCESS: "Rol eliminado exitosamente",
  ROLE_DELETE_ERROR: "Error al eliminar el rol",
  
  // Common UI
  NO_RESULTS: "No se encontraron resultados",
  NO_RESULTS_DESCRIPTION: "Intenta ajustar los filtros de búsqueda",
  LOADING: "Cargando...",
};

export const ERRORS = {
  // Error page
  ERROR_TITLE: "¡Oops! Algo salió mal",
  ERROR_SUBTITLE: "Ha ocurrido un error inesperado. Nuestro equipo ha sido notificado y estamos trabajando para solucionarlo.",
  ERROR_CODE: "Código de Error",
  GO_HOME: "Ir al Inicio",
  RELOAD: "Recargar",
  CONTACT_SUPPORT: "Si el problema persiste, contacta a soporte técnico",
  
  // Forbidden page
  FORBIDDEN_TITLE: "Acceso Denegado",
  FORBIDDEN_SUBTITLE: "No tienes permisos para acceder a esta página. Contacta a tu administrador si crees que esto es un error.",
  ACCESS_DENIED: "Acceso Denegado",
  CONTACT_ADMIN: "Contacta a tu administrador",
  
  // Not Found page
  NOT_FOUND_TITLE: "Página No Encontrada",
  NOT_FOUND_SUBTITLE: "La página que buscas no existe o ha sido movida.",
  PAGE_NOT_FOUND: "Página No Encontrada",
  
  // Session Expired
  SESSION_EXPIRED_TITLE: "Sesión Expirada",
  SESSION_EXPIRED_SUBTITLE: "Tu sesión ha caducado",
  SESSION_EXPIRED_DESCRIPTION: "Por razones de seguridad, tu sesión ha expirado automáticamente. Por favor, inicia sesión nuevamente para continuar.",
  SESSION_EXPIRED_BUTTON: "Iniciar Sesión",
  SESSION_EXPIRED_CAPTION: "Esta es una medida de seguridad para proteger tu cuenta",
  ERROR_500_TITLE: "Error 500",
  ERROR_500_SUBTITLE: "Oops, algo salió mal",
  ERROR_500_DESCRIPTION: "Ha ocurrido un error inesperado en nuestro servidor. Nuestro equipo técnico ha sido notificado y está trabajando para solucionarlo.",
  ERROR_403_TITLE: "Error 403",
  ERROR_403_SUBTITLE: "Acceso Denegado",
  ERROR_403_DESCRIPTION: "No tienes los permisos necesarios para acceder a esta página. Si crees que esto es un error, contacta a tu administrador.",
  ERROR_403_CONTACT: "Para solicitar acceso adicional, contacta a tu administrador del sistema",
  ERROR_404_TITLE: "404",
  ERROR_404_SUBTITLE: "Página no encontrada",
  ERROR_404_DESCRIPTION: "Lo sentimos, la página que estás buscando no existe o ha sido movida. Verifica la URL o navega a una página diferente.",
  ERROR_404_EXPLORE: "Explorar",
  ERROR_404_CONTACT: "Si crees que esto es un error, contacta a soporte técnico",
};

export const DIALOG = {
  // Button texts
  DELETE: "Eliminar",
  CONTINUE: "Continuar",
  ACCEPT: "Aceptar",
  CONFIRM: "Confirmar",
  CANCEL: "Cancelar",
  
  // Common actions
  CLOSE: "Cerrar",
  SAVE: "Guardar",
  UPDATE: "Actualizar",
  
  // Confirmation messages
  CONFIRM_DELETE: "¿Estás seguro de que deseas eliminar este elemento?",
  CONFIRM_ACTION: "¿Estás seguro de que deseas realizar esta acción?",
  
  // Success messages
  SUCCESS_TITLE: "Operación Exitosa",
  SUCCESS_MESSAGE: "La operación se completó correctamente",
  
  // Warning messages
  WARNING_TITLE: "Advertencia",
  WARNING_MESSAGE: "Esta acción no se puede deshacer",
  
  // Info messages
  INFO_TITLE: "Información",
  INFO_MESSAGE: "Información importante",
};

export const TABLE_UI = {
  // Common table actions
  EDIT: "Editar",
  DELETE: "Eliminar",
  VIEW: "Ver",
  VIEW_MORE: "Ver más",
  VIEW_LESS: "Ver menos",
  
  // Table headers
  ACTIONS: "Acciones",
  NO_DATA: "No hay datos disponibles",
  LOADING_DATA: "Cargando datos...",
  
  // Pagination
  ROWS_PER_PAGE: "Filas por página",
  OF: "de",
  SHOWING: "Mostrando",
  TO: "a",
  ENTRIES: "registros",
  
  // Sorting
  SORT_ASC: "Ordenar ascendente",
  SORT_DESC: "Ordenar descendente",
  
  // Selection
  SELECT_ALL: "Seleccionar todo",
  DESELECT_ALL: "Deseleccionar todo",
  SELECTED: "seleccionados",
  
  // Filters
  FILTER: "Filtrar",
  CLEAR_FILTERS: "Limpiar filtros",
  SEARCH: "Buscar",
  SEARCH_PLACEHOLDER: "Buscar...",
  
  // Export
  EXPORT_EXCEL: "Exportar a Excel",
  EXPORT_PDF: "Exportar a PDF",
  EXPORT_CSV: "Exportar a CSV",
  
  // Status
  ACTIVE: "Activo",
  INACTIVE: "Inactivo",
  ENABLED: "Habilitado",
  DISABLED: "Deshabilitado",
  
  // Common fields
  NAME: "Nombre",
  DESCRIPTION: "Descripción",
  CREATED_AT: "Creado el",
  UPDATED_AT: "Actualizado el",
  STATUS: "Estado",
};

export const DASHBOARD = {
  USERS: "Usuarios",
  ROLES: "Roles",
  PERMISSIONS: "Permisos",
};

export const SNACKBAR = {
  CLOSE: "Cerrar",
};

export const PAGES = {
  VEHICLES: {
    TITLE: "Vehículos",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo vehículo",
    DELETE_TITLE: "Eliminar Vehículo",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este vehículo? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron vehículos para mostrar.",
    CREATED_SUCCESS: "Vehículo creado exitosamente",
    CREATED_ERROR: "Error al crear el vehículo",
  },
  EMPLOYEES: {
    TITLE: "Empleados",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo empleado",
    DELETE_TITLE: "Eliminar Empleado",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este empleado? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron empleados para mostrar.",
    CREATED_SUCCESS: "El registro del empleado fue exitoso",
    CREATED_ERROR: "Ha ocurrido un error al registrar el empleado",
    UPDATED_SUCCESS: "La actualización del empleado fue exitosa",
    UPDATED_ERROR: "Ha ocurrido un error al actualizar el empleado",
  },
  ROLES: {
    TITLE: "Roles",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo rol",
    DELETE_TITLE: "Eliminar Rol",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este rol? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron roles para mostrar.",
    CREATED_SUCCESS: "El registro del rol fue exitoso",
    CREATED_ERROR: "Ha ocurrido un error al registrar el rol",
    UPDATED_SUCCESS: "La actualización del rol fue exitosa",
    UPDATED_ERROR: "Ha ocurrido un error al actualizar el rol",
  },
  SCHEDULES: {
    TITLE: "Horarios",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo horario",
    DELETE_TITLE: "Eliminar Horario",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este horario? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron horarios para mostrar.",
    CREATED_SUCCESS: "El registro del horario fue exitoso",
    CREATED_ERROR: "Ha ocurrido un error al registrar el horario",
    UPDATED_SUCCESS: "La actualización del horario fue exitosa",
    UPDATED_ERROR: "Ha ocurrido un error al actualizar el horario",
  },
  COURIERS: {
    TITLE: "Servicios de Mensajería",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo servicio",
    DELETE_TITLE: "Eliminar Servicio",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este servicio de mensajería? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron servicios de mensajería para mostrar.",
    CREATED_SUCCESS: "Servicio de mensajería creado exitosamente",
    CREATED_ERROR: "Error al crear el servicio de mensajería",
  },
  USERS: {
    TITLE: "Usuarios",
    ADD_BUTTON: "Agregar",
    ADD_SUBTITLE: "Nuevo usuario",
    DELETE_TITLE: "Eliminar Usuario",
    DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este usuario? Esta acción no se puede deshacer.",
    DELETE_CONFIRM: "Eliminar",
    DELETE_CANCEL: "Cancelar",
    NO_RESULTS: "No se encontraron usuarios para mostrar.",
    CREATED_SUCCESS: "Usuario creado exitosamente",
    CREATED_ERROR: "Error al crear el usuario",
    UPDATED_SUCCESS: "La actualización del usuario fue exitosa",
    UPDATED_ERROR: "Ha ocurrido un error al actualizar el usuario",
  },
  COMMON: {
    SELECT_DATE: "Seleccionar fecha",
    NO_RESULTS: "No se encontraron resultados para mostrar.",
    CANCEL: "Cancelar",
    CONFIRM: "Confirmar",
    SAVE: "Guardar",
    EDIT: "Editar",
    DELETE: "Eliminar",
    CLOSE: "Cerrar",
    SEARCH: "Buscar...",
  },
};

export const LOGIN = {
  IDENTIFIER_LABEL: "Correo Electrónico o Usuario",
  PASSWORD_LABEL: "Contraseña",
  LOADING: "Iniciando sesión...",
  SUBMIT: "Iniciar Sesión",
  NO_ACCOUNT: "¿Aún no tienes una cuenta?",
  REGISTER_LINK: "Regístrate aquí",
};

export const SEARCH_BAR = {
  PLACEHOLDER: "Buscar...",
};

export const PAGINATION = {
  PAGE: "Página",
  OF: "de",
  PREVIOUS: "Página anterior",
  NEXT: "Página siguiente",
};

export const DASHBOARD_USERS = {
  LOAD_ERROR_TITLE: "Error de Carga",
  LOAD_ERROR_RETRY: "Reintentar",
  SEARCH_PLACEHOLDER: "Buscar usuario",
  SHOW_INACTIVE: "Mostrando Inactivos",
  HIDE_INACTIVE: "Ocultar Inactivos",
  ADD: "Agregar",
  NO_USERS: "No se encontraron usuarios para mostrar.",
  DIALOG_STATUS_TITLE: "Cambiar Estado de Usuario",
  DIALOG_STATUS_MESSAGE: "¿Estás seguro de que deseas cambiar el estado de este usuario?",
  DIALOG_STATUS_CONFIRM: "Cambiar Estado",
  DIALOG_STATUS_CANCEL: "Cancelar",
  DIALOG_PASSWORD_TITLE: "Cambiar Contraseña para Usuario ID:",
  DIALOG_PASSWORD_SUBTITLE: "Ingresa una nueva contraseña para este usuario.",
  DIALOG_PASSWORD_NEW: "Nueva Contraseña",
  DIALOG_PASSWORD_NEW_PLACEHOLDER: "Mínimo 8 caracteres",
  DIALOG_PASSWORD_CONFIRM: "Confirmar Nueva Contraseña",
  DIALOG_PASSWORD_CONFIRM_PLACEHOLDER: "Repite la nueva contraseña",
  DIALOG_PASSWORD_CANCEL: "Cancelar",
  DIALOG_PASSWORD_CHANGE: "Cambiar Contraseña",
};

export const DASHBOARD_ROLES = {
  SEARCH_PLACEHOLDER: "Buscar rol",
  ADD: "Agregar",
  NO_ROLES: "No se encontraron roles para mostrar.",
  DIALOG_DELETE_TITLE: "Eliminar Rol",
  DIALOG_DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este rol? Esta acción no se puede deshacer.",
  DIALOG_DELETE_CONFIRM: "Eliminar",
  DIALOG_DELETE_CANCEL: "Cancelar",
  DIALOG_ADD_TITLE: "Agregar",
  DIALOG_ADD_SUBTITLE: "Nuevo rol",
};

export const DASHBOARD_PERMISSIONS = {
  SEARCH_PLACEHOLDER: "Buscar permiso",
  NO_PERMISSIONS: "No se encontraron permisos para mostrar.",
};

export const EMPLOYEES_PAGE = {
  SEARCH_PLACEHOLDER: "Buscar empleado",
  ADD: "Agregar",
  NO_EMPLOYEES: "No se encontraron empleados para mostrar.",
  DIALOG_DELETE_TITLE: "Eliminar Empleado",
  DIALOG_DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este empleado? Esta acción no se puede deshacer.",
  DIALOG_DELETE_CONFIRM: "Eliminar",
  DIALOG_DELETE_CANCEL: "Cancelar",
  DIALOG_ADD_TITLE: "Agregar",
  DIALOG_ADD_SUBTITLE: "Nuevo empleado",
};

export const ROLES_PAGE = {
  SEARCH_PLACEHOLDER: "Buscar empleado",
  DATE_PICKER_LABEL: "Seleccionar fecha",
  TOOLTIP_PREV_WEEK: "Semana Anterior",
  TOOLTIP_NEXT_WEEK: "Semana Siguiente",
  TOOLTIP_CURRENT_WEEK: "Semana Actual",
  NO_EMPLOYEES: "No se encontraron empleados para mostrar.",
  DIALOG_EXPORT_TITLE: "Exportar Horas",
  DIALOG_EXPORT_MESSAGE_EXCEL: "¿Quieres que se incluyan las horas trabajadas al exportar el excel?",
  DIALOG_EXPORT_MESSAGE_PDF: "¿Quieres que se incluyan las horas trabajadas al exportar el pdf?",
  DIALOG_EXPORT_CONFIRM: "Sí, incluir horas",
  DIALOG_EXPORT_CANCEL: "No, solo datos básicos",
  SUMMARY_TITLE: "Resumen de Horas Trabajadas",
  SUMMARY_WEEKLY: "Horas trabajadas esta semana",
  SUMMARY_BIWEEKLY: "Horas trabajadas esta quincena",
  SUMMARY_MONTHLY: "Horas trabajadas este mes",
  SUMMARY_OVERTIME: "Horas Extra",
  SUMMARY_DETAIL_OVERTIME: "Detalle de horas extra por periodo",
  SUMMARY_INFO_TITLE: "Información de Resumen",
  SUMMARY_INFO_DESC: "Consulta el total de horas trabajadas por periodo. Usa las pestañas para cambiar entre semana, quincena, mes y horas extra.",
  TAB_WEEKLY: "Semanal",
  TAB_BIWEEKLY: "Quincenal",
  TAB_MONTHLY: "Mensual",
  TAB_OVERTIME: "Horas Extra",
};

export const SCHEDULES_PAGE = {
  SEARCH_PLACEHOLDER: "Buscar horario",
  ADD: "Agregar",
  NO_SCHEDULES: "No se encontraron horarios para mostrar.",
  DIALOG_DELETE_TITLE: "Eliminar Horario",
  DIALOG_DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este horario? Esta acción no se puede deshacer.",
  DIALOG_DELETE_CONFIRM: "Eliminar",
  DIALOG_DELETE_CANCEL: "Cancelar",
  DIALOG_ADD_TITLE: "Agregar",
  DIALOG_ADD_SUBTITLE: "Nuevo horario",
};

export const VEHICLES_PAGE = {
  SEARCH_PLACEHOLDER: "Buscar vehículo",
  ADD: "Agregar",
  DATE_PICKER_LABEL: "Seleccionar fecha",
  TOOLTIP_PREV_DAY: "Día Anterior",
  TOOLTIP_NEXT_DAY: "Día Siguiente",
  TOOLTIP_CURRENT_DAY: "Día Actual",
  NO_VEHICLES: "No se encontraron vehículos para mostrar.",
  DIALOG_DELETE_TITLE: "Eliminar Vehículo",
  DIALOG_DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este vehículo? Esta acción no se puede deshacer.",
  DIALOG_DELETE_CONFIRM: "Eliminar",
  DIALOG_DELETE_CANCEL: "Cancelar",
  DIALOG_ADD_TITLE: "Agregar",
  DIALOG_ADD_SUBTITLE: "Nuevo vehículo",
};

export const COURIER_SERVICE_PAGE = {
  SEARCH_PLACEHOLDER: "Buscar servicio",
  ADD: "Agregar",
  DATE_PICKER_LABEL: "Seleccionar fecha",
  TOOLTIP_PREV_DAY: "Día Anterior",
  TOOLTIP_NEXT_DAY: "Día Siguiente",
  TOOLTIP_CURRENT_DAY: "Día Actual",
  NO_SERVICES: "No se encontraron servicios de mensajería para mostrar.",
  DIALOG_DELETE_TITLE: "Eliminar Servicio",
  DIALOG_DELETE_MESSAGE: "¿Estás seguro de que deseas eliminar este servicio de mensajería? Esta acción no se puede deshacer.",
  DIALOG_DELETE_CONFIRM: "Eliminar",
  DIALOG_DELETE_CANCEL: "Cancelar",
  DIALOG_ADD_TITLE: "Agregar",
  DIALOG_ADD_SUBTITLE: "Nuevo servicio",
};

export const REGISTER_VALIDATION = {
  FIRST_NAME_INVALID: "El nombre solo puede contener letras, espacios y puntos",
  LAST_NAME_INVALID: "El apellido solo puede contener letras, espacios y puntos",
  USERNAME_INVALID: "El usuario debe comenzar con una letra y tener 3-20 caracteres",
  PASSWORD_INVALID: "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  REGISTER_ERROR: "Error al registrar usuario",
};

export const SETTINGS_PAGE = {
  PERSONAL_INFO_TITLE: "Información Personal",
  PERSONAL_INFO_DESC: "Modifica tu información personal y correo electrónico.",
  RECOMMENDATION_TITLE: "Recomendación",
  RECOMMENDATION_DESC: "Verifica que tus datos sean correctos antes de guardar los cambios.",
  SAVE_CHANGES: "Guardar Cambios",
  PASSWORD_TITLE: "Cambiar Contraseña",
  PASSWORD_DESC: "Ingresa una nueva contraseña para tu cuenta.",
  NEW_PASSWORD_LABEL: "Nueva contraseña",
  CONFIRM_NEW_PASSWORD_LABEL: "Confirmar nueva contraseña",
  SECURITY_TIP_TITLE: "Consejo de seguridad",
  SECURITY_TIP_DESC: "Usa una contraseña única y no la compartas con nadie.\nDebe tener mínimo 8 caracteres, una mayúscula y un número.",
  CHANGE_PASSWORD: "Cambiar Contraseña",
  EMAIL_EXISTS: "El correo electrónico ya existe.",
  USERNAME_EXISTS: "El nombre de usuario ya existe.",
  UPDATE_SUCCESS: "La actualización de lo datos fue exitosa",
  UPDATE_ERROR: "Ha ocurrido un error al actualizar los datos",
  PASSWORD_UPDATE_SUCCESS: "La actualización de la contraseña fue exitosa",
  PASSWORD_UPDATE_ERROR: "Ha ocurrido un error al actualizar la contraseña",
};
