export const ROUTES = {
  LOGIN: "/",
  REGISTER: "register",
  ROLES: "/roles",
  VEHICLES: "/vehicles",
  EMPLOYEES: "/employees",
  SCHEDULES: "/schedules",
  DASHBOARD: "/dashboard",
};

export const APPBAR_MENU = {
  TITLE: "Choferes",
  ROLES: "Roles",
  VEHICLES: "Vehículos",
  MANAGE: "Gestión",
  EMPLOYEES: "Empleados",
  SCHEDULES: "Horarios",
  DASHBOARD: "Admin",
  LOGOUT: "Salir",
};

export const PAGE_TITLE = {
  LOGIN: "Iniciar Sesión",
  REGISTER: "Registrar Usuario",
  ROLES: "Gestionar Roles",
  VEHICLES: "Gestionar Vehículos",
  EMPLOYEES: "Gestionar Empleados",
  SCHEDULES: "Gestionar Horarios",
  DASHBOARD: "Panel de Administración",
  ROLES_SIMPLIFIED: "Roles",
  VEHICLES_SIMPLIFIED: "Vehículos",
  EMPLOYEES_SIMPLIFIED: "Empleados",
  SCHEDULES_SIMPLIFIED: "Horarios",
  DASHBOARD_SIMPLIFIED: "Administración",
};

export const PERMISSIONS = {
  VIEW_ROLES: "Ver Roles",
  VIEW_EMPLOYEE_ROLES_HOURS: "Ver Horas de Empleados",
  EDIT_EMPLOYEE_ROLES: "Editar Roles de Empleados",
  EXPORT_EXCEL_ROLES: "Exportar Excel de Roles de Empleados",
  EXPORT_PDF_ROLES: "Exportar PDF de Roles de Empleados",
  VIEW_EMPLOYEES: "Ver Empleados",
  CREATE_EMPLOYEES: "Crear Empleado",
  EDIT_EMPLOYEES: "Editar Empleado",
  DELETE_EMPLOYEES: "Eliminar Empleado",
  EXPORT_EXCEL_EMPLOYEES: "Exportar Excel de Empleados",
  EXPORT_PDF_EMPLOYEES: "Exportar PDF de Empleados",
  VIEW_SCHEDULES: "Ver Horarios",
  CREATE_SCHEDULES: "Crear Horario",
  EDIT_SCHEDULES: "Editar Horario",
  DELETE_SCHEDULES: "Eliminar Horario",
  EXPORT_EXCEL_SCHEDULES: "Exportar Excel de Horarios",
  EXPORT_PDF_SCHEDULES: "Exportar PDF de Horarios",
  VIEW_VEHICLES: "Ver Vehículos",
  CREATE_VEHICLES: "Crear Vehículo",
  EDIT_VEHICLES: "Editar Vehículo",
  DELETE_VEHICLES: "Eliminar Vehículo",
  EXPORT_EXCEL_VEHICLES: "Exportar Excel de Vehículos",
  EXPORT_PDF_VEHICLES: "Exportar PDF de Vehículos",
  VIEW_ADMIN: "Ver Admin",
  EDIT_USER: "Editar Usuario",
  DELETE_USER: "Eliminar Usuario",
  CREATE_ROLE: "Crear Rol",
  EDIT_ROLE: "Editar Rol",
  DELETE_ROLE: "Eliminar Rol",
};

export const DAYS_LIST = [
  { value: "monday", label: "Lunes" },
  { value: "tuesday", label: "Martes" },
  { value: "wednesday", label: "Miércoles" },
  { value: "thursday", label: "Jueves" },
  { value: "friday", label: "Viernes" },
  { value: "saturday", label: "Sábado" },
  { value: "sunday", label: "Domingo" },
];

export const ROLES_LIST = [
  { value: "Gerencia", label: "Gerencia" },
  { value: "Administrativo", label: "Administrativo" },
  { value: "Supervisor", label: "Supervisor" },
  { value: "Usuario", label: "Usuario" },
];

export const PERMISSIONS_LIST = [
  { value: "Ver Roles", label: "Ver Roles" },
  { value: "Ver Horas de Empleados", label: "Ver Horas de Empleados" },
  { value: "Editar Roles de Empleados", label: "Editar Roles de Empleados" },
  {
    value: "Exportar Excel de Roles de Empleados",
    label: "Exportar Excel de Roles de Empleados",
  },
  {
    value: "Exportar PDF de Roles de Empleados",
    label: "Exportar PDF de Roles de Empleados",
  },
  { value: "Ver Empleados", label: "Ver Empleados" },
  { value: "Crear Empleado", label: "Crear Empleado" },
  { value: "Editar Empleado", label: "Editar Empleado" },
  { value: "Eliminar Empleado", label: "Eliminar Empleado" },
  {
    value: "Exportar Excel de Empleados",
    label: "Exportar Excel de Empleados",
  },
  { value: "Exportar PDF de Empleados", label: "Exportar PDF de Empleados" },
  { value: "Ver Horarios", label: "Ver Horarios" },
  { value: "Crear Horario", label: "Crear Horario" },
  { value: "Editar Horario", label: "Editar Horario" },
  { value: "Eliminar Horario", label: "Eliminar Horario" },
  { value: "Exportar Excel de Horarios", label: "Exportar Excel de Horarios" },
  { value: "Exportar PDF de Horarios", label: "Exportar PDF de Horarios" },
  { value: "Ver Vehículos", label: "Ver Vehículos" },
  { value: "Crear Vehículo", label: "Crear Vehículo" },
  { value: "Editar Vehículo", label: "Editar Vehículo" },
  { value: "Eliminar Vehículo", label: "Eliminar Vehículo" },
  {
    value: "Exportar Excel de Vehículos",
    label: "Exportar Excel de Vehículos",
  },
  { value: "Exportar PDF de Vehículos", label: "Exportar PDF de Vehículos" },
  { value: "Ver Admin", label: "Ver Admin" },
  { value: "Editar Usuario", label: "Editar Usuario" },
  { value: "Eliminar Usuario", label: "Eliminar Usuario" },
  { value: "Crear Rol", label: "Crear Rol" },
  { value: "Editar Rol", label: "Editar Rol" },
  { value: "Eliminar Rol", label: "Eliminar Rol" },
];

export const DAYS = {
  WEEKDAY: "weekday",
  MONDAY: "monday",
  TUESDAY: "tuesday",
  WEDNESDAY: "wednesday",
  THURSDAY: "thursday",
  FRIDAY: "friday",
  SATURDAY: "saturday",
  SUNDAY: "sunday",
};

export const OVERTIME = {
  WEEKLY: 48,
  BIWEEKLY: 96,
  MONTHLY: 192,
};

export const COLORS_LIST = [
  { value: "Blanco", label: "Blanco" },
  { value: "Negro", label: "Negro" },
  { value: "Gris", label: "Gris" },
  { value: "Azul", label: "Azul" },
  { value: "Rojo", label: "Rojo" },
  { value: "Verde", label: "Verde" },
  { value: "Amarillo", label: "Amarillo" },
  { value: "Naranja", label: "Naranja" },
  { value: "Café", label: "Café" },
  { value: "Plateado", label: "Plateado" },
  { value: "Dorado", label: "Dorado" },
  { value: "Vino", label: "Vino" },
  { value: "Beige", label: "Beige" },
  { value: "Morado", label: "Morado" },
  { value: "Turquesa", label: "Turquesa" },
  { value: "Púrpura", label: "Púrpura" },
  { value: "Celeste", label: "Celeste" },
  { value: "Bronce", label: "Bronce" },
  { value: "Champán", label: "Champán" },
];

export const BRANDS_LIST = [
  { value: "Acura", label: "Acura" },
  { value: "Alfa Romeo", label: "Alfa Romeo" },
  { value: "Aston Martin", label: "Aston Martin" },
  { value: "Audi", label: "Audi" },
  { value: "BMW", label: "BMW" },
  { value: "Bugatti", label: "Bugatti" },
  { value: "Buick", label: "Buick" },
  { value: "BYD", label: "BYD" },
  { value: "Cadillac", label: "Cadillac" },
  { value: "Changan", label: "Changan" },
  { value: "Chevrolet", label: "Chevrolet" },
  { value: "Chery", label: "Chery" },
  { value: "Chrysler", label: "Chrysler" },
  { value: "Citroën", label: "Citroën" },
  { value: "Dodge", label: "Dodge" },
  { value: "Dongfeng", label: "Dongfeng" },
  { value: "Ferrari", label: "Ferrari" },
  { value: "Fiat", label: "Fiat" },
  { value: "Ford", label: "Ford" },
  { value: "Foton", label: "Foton" },
  { value: "Geely", label: "Geely" },
  { value: "GMC", label: "GMC" },
  { value: "Great Wall", label: "Great Wall" },
  { value: "Haval", label: "Haval" },
  { value: "Honda", label: "Honda" },
  { value: "Hummer", label: "Hummer" },
  { value: "Hyundai", label: "Hyundai" },
  { value: "Infiniti", label: "Infiniti" },
  { value: "Isuzu", label: "Isuzu" },
  { value: "Jac", label: "Jac" },
  { value: "Jaguar", label: "Jaguar" },
  { value: "Jeep", label: "Jeep" },
  { value: "Kia", label: "Kia" },
  { value: "Land Rover", label: "Land Rover" },
  { value: "Lamborghini", label: "Lamborghini" },
  { value: "Lexus", label: "Lexus" },
  { value: "Lincoln", label: "Lincoln" },
  { value: "Lucid", label: "Lucid" },
  { value: "Maserati", label: "Maserati" },
  { value: "Mazda", label: "Mazda" },
  { value: "McLaren", label: "McLaren" },
  { value: "Mercedes-Benz", label: "Mercedes-Benz" },
  { value: "MG", label: "MG" },
  { value: "Mini", label: "Mini" },
  { value: "Mitsubishi", label: "Mitsubishi" },
  { value: "Nissan", label: "Nissan" },
  { value: "Pagani", label: "Pagani" },
  { value: "Peugeot", label: "Peugeot" },
  { value: "Porsche", label: "Porsche" },
  { value: "Ram", label: "Ram" },
  { value: "Renault", label: "Renault" },
  { value: "Rivian", label: "Rivian" },
  { value: "Rolls-Royce", label: "Rolls-Royce" },
  { value: "Saab", label: "Saab" },
  { value: "Seat", label: "Seat" },
  { value: "Subaru", label: "Subaru" },
  { value: "Suzuki", label: "Suzuki" },
  { value: "Tesla", label: "Tesla" },
  { value: "Toyota", label: "Toyota" },
  { value: "Volkswagen", label: "Volkswagen" },
  { value: "Volvo", label: "Volvo" },
  { value: "Wuling", label: "Wuling" },
  { value: "Xpeng", label: "Xpeng" },
];

export const STATE = {
  FREE: "Libre",
};

export const TABLE = {
  ROWS_PER_PAGE: "Filas por página",
};
