const FORMS = {
  ALREADY_REGISTERED: "Ya está registrado",
  DAYS_REQUIRED: "Debe seleccionar al menos un día",
  DISTANCE_GREATER_0: "La distancia debe ser mayor a 0",
  DISTANCE_MAX_1000: "La distancia no puede ser mayor a 1000 km",
  EMAIL_EXISTS: "El correo electrónico ya existe",
  EMAIL_FORMAT: "El correo electrónico no tiene un formato válido",
  EMAIL_INVALID: "El correo electrónico no tiene un formato válido",
  EMAIL_REQUIRED: "El correo electrónico es requerido",
  FIRST_NAME: "Nombre",
  FIRST_NAME_REQUIRED: "El nombre es requerido",
  HOURS_INVALID: "Las horas deben ser un número entre 1 y 24",
  HOURS_REQUIRED: "Las horas son requeridas",
  INVALID_FORMAT_EXAMPLE: "Formato inválido. Ejemplo: 123ABC",
  INVALID_FORMAT_PARKING: "Formato inválido. Ejemplo: A-12",
  LABEL_REQUIRED: "Etiqueta requerida",
  LAST_NAME: "Apellido",
  LAST_NAME_REQUIRED: "El apellido es requerido",
  LETTERS_SPACES_HYPHENS: "Solo se permiten letras, espacios y guiones",
  LICENSE_PLATE_ALREADY_REGISTERED: "La placa ya está registrada",
  LOGIN_DESCRIPTION: "Ingresa tus credenciales para acceder al sistema",
  MAX_100_CHARS: "No puede tener más de 100 caracteres",
  MAX_30_CHARS: "No puede tener más de 30 caracteres",
  MAX_50_CHARS: "No puede tener más de 50 caracteres",
  MIN_2_CHARS: "Debe tener al menos 2 caracteres",
  MIN_3_CHARS: "Debe tener al menos 3 caracteres",
  NAME_LETTERS_ONLY: "Solo se permiten letras, espacios y guiones",
  PASSWORD_COMPLEXITY: "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_INVALID: "La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial",
  PASSWORD_REQUIRED: "La contraseña es requerida",
  PASSWORDS_DONT_MATCH: "Las contraseñas no coinciden",
  PASSWORDS_REQUIRED: "Ambas contraseñas son requeridas",
  POSITIVE_NUMBER_ONLY: "Solo se permiten números positivos",
  REQUIRED_FIELD: "Este campo es requerido",
  ROLE_REQUIRED: "El rol es requerido",
  TRACKING_MAX_50: "No puede tener más de 50 caracteres",
  TRACKING_MIN_3: "Debe tener al menos 3 caracteres",
  USERNAME_EXISTS: "El nombre de usuario ya existe",
  USERNAME_FORMAT: "El usuario debe comenzar con una letra y tener entre 3 y 20 caracteres",
  USERNAME_INVALID: "El usuario debe comenzar con una letra y tener 3-20 caracteres",
  USERNAME_REQUIRED: "El usuario es requerido",
  USERNAME_START_LETTER: "El usuario debe comenzar con una letra",
  ADD_USER: {
    INFO_TITLE: "Información del Usuario",
    INFO_DESC: "Completa todos los campos para crear un nuevo usuario. La contraseña debe tener al menos 8 caracteres, una mayúscula, una minúscula, un número y un carácter especial.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    EMAIL_LABEL: "Email",
    EMAIL_PLACEHOLDER: "Ej: juan.perez@empresa.com",
    USERNAME_LABEL: "Nombre de Usuario",
    USERNAME_PLACEHOLDER: "Ej: juan.perez",
    PASSWORD_LABEL: "Contraseña",
    PASSWORD_PLACEHOLDER: "Mínimo 8 caracteres",
    ROLE_LABEL: "Rol",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_EMPLOYEE: {
    INFO_TITLE: "Información del Empleado",
    INFO_DESC: "Ingresa el nombre completo del empleado. Solo se permiten letras, espacios y guiones.",
    FIRST_NAME_LABEL: "Nombre",
    FIRST_NAME_PLACEHOLDER: "Ej: Juan Carlos",
    LAST_NAME_LABEL: "Apellido",
    LAST_NAME_PLACEHOLDER: "Ej: Pérez González",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_ROLE: {
    INFO_TITLE: "Información del Rol",
    INFO_DESC: "Define el nombre y permisos del nuevo rol. Los permisos determinan qué acciones puede realizar un usuario con este rol en el sistema.",
    NAME_LABEL: "Nombre del Rol",
    NAME_PLACEHOLDER: "Ej: Administrador",
    PERMISSIONS_LABEL: "Permisos del Rol",
    PERMISSIONS_SELECTED: (count: number) => `Permisos Seleccionados (${count})`,
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
  ADD_VEHICLE: {
    INFO_TITLE: "Información Importante",
    INFO_DESC: "Completa todos los campos requeridos. La boleta y placa deben ser únicas.",
    INFO_OPTIONAL: 'Puedes usar "N/A" para campos opcionales.',
    TICKET_LABEL: "Boleta",
    TICKET_PLACEHOLDER: "Ej: 12345",
    LICENSE_PLATE_LABEL: "Placa",
    LICENSE_PLATE_PLACEHOLDER: "Ej: ABC-123",
    BRAND_LABEL: "Marca",
    COLOR_LABEL: "Color",
    PARKING_LOT_LABEL: "Espacio de Parqueo",
    PARKING_LOT_PLACEHOLDER: "Ej: ATP1-123",
    PARKING_DATE_LABEL: "Fecha de Parqueo",
    OBSERVATIONS_LABEL: "Observaciones",
    OBSERVATIONS_PLACEHOLDER: "Observaciones adicionales sobre el vehículo...",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
    NO_OPTIONS: "Sin coincidencias",
  },
  ADD_COURIER: {
    INFO_TITLE: "Información del Servicio de Mensajería",
    INFO_DESC: "Completa todos los campos requeridos para registrar un nuevo servicio de mensajería.",
    DRIVER: "Chofer",
    DRIVER_PLACEHOLDER: "Ej: Juan Pérez",
    ROUTE: "Ruta",
    DISTANCE: "Distancia (km)",
    DISTANCE_PLACEHOLDER: "Ej: 45",
    TRACKING_NUMBER: "Número de Guía",
    TRACKING_NUMBER_PLACEHOLDER: "Ej: TRK001",
    STATUS: "Estado",
    STATUS_DESPACHADO: "Despachado",
    STATUS_EN_TRANSITO: "En Tránsito",
    STATUS_ENTREGADO: "Entregado",
    CLEAR_BUTTON: "Limpiar",
    CANCEL_BUTTON: "Cancelar",
    LOADING_BUTTON: "Agregando...",
    ADD_BUTTON: "Agregar",
  },
  ADD_SCHEDULE: {
    SCHEDULE_LABEL: "Horario/Lugar",
    SCHEDULE_LABEL_PLACEHOLDER: "Ej: Avenida 123",
    SCHEDULE_TIME_LABEL: "Tiempo",
    SCHEDULE_TIME_PLACEHOLDER: "Ej: 8",
    SPECIAL_LABEL: "Horario Especial",
    SPECIAL_DESC: "Marque esta opción si es un horario con condiciones especiales",
    BUTTON_ADD: "Agregar",
    BUTTON_ADDING: "Agregando...",
  },
};
export default FORMS; 