const LOGIN = {
  IDENTIFIER_LABEL: "Correo o usuario",
  PASSWORD_LABEL: "Contraseña",
  LOADING: "Ingresando...",
  SUBMIT: "Ingresar",
  NO_ACCOUNT: "¿No tienes cuenta?",
  REGISTER_LINK: "Regístrate aquí",
  EMAIL_OR_USERNAME: "Correo o usuario",
  EMAIL_OR_USERNAME_REQUIRED: "El correo o usuario es requerido",
  PASSWORD: "Contraseña",
  LOGIN: "Iniciar sesión",
  LOGGING_IN: "Ingresando...",
  PERSONAL_INFO: "Información personal",
  PERSONAL_INFO_DESCRIPTION: "Actualiza tus datos personales aquí.",
  FIRST_NAME: "Nombre",
  LAST_NAME: "Apellido",
  EMAIL: "Correo electrónico",
  USERNAME: "Usuario",
  PASSWORD_REQUIRED: "La contraseña es requerida",
  REGISTER_ERROR: "Error al registrarse",
  SERVER: "Despertando servidor... Esto puede tomar unos minutos",
  ACCESS_RESTRICTED: "Acceso exclusivo para personal autorizado",
  FLEET_MANAGEMENT: "Controla tu flota de choferes desde un solo lugar.",
  FORGOT_PASSWORD_TITLE: "Recuperar contraseña",
  FORGOT_PASSWORD_DESC: "Ingresa tu correo electrónico y te enviaremos un enlace para restablecer tu contraseña.",
  SEND_RESET_LINK: "Enviar enlace",
  BACK_TO_LOGIN: "Volver a iniciar sesión",
};
export default LOGIN;
