const NOTIFICATIONS = {
  USER_CREATED: "Usuario creado exitosamente",
  USER_UPDATED: "Usuario actualizado exitosamente",
  USER_DELETED: "Usuario eliminado exitosamente",
  EMPLOYEE_CREATED: "El registro del empleado fue exitoso",
  EMPLOYEE_UPDATED: "La actualización del empleado fue exitosa",
  EMPLOYEE_DELETED: "Empleado eliminado exitosamente",
  SCHEDULE_CREATED: "El registro del horario fue exitoso",
  SCHEDULE_UPDATED: "La actualización del horario fue exitosa",
  SCHEDULE_DELETED: "Horario eliminado exitosamente",
  VEHICLE_CREATED: "El registro del vehículo fue exitoso",
  VEHICLE_UPDATED: "La actualización del vehículo fue exitosa",
  VEHICLE_DELETED: "Vehículo eliminado exitosamente",
  ROLE_CREATED: "El registro del rol fue exitoso",
  ROLE_UPDATED: "La actualización del rol fue exitosa",
  ROLE_DELETED: "Rol eliminado exitosamente",
  USER_REGISTERED: "El registro del usuario fue exitoso",
  DATA_UPDATED: "La actualización de los datos fue exitosa",
  PASSWORD_UPDATED: "La actualización de la contraseña fue exitosa",
  USER_CREATE_ERROR: "Error al crear el usuario",
  USER_UPDATE_ERROR: "Error al actualizar el usuario",
  USER_DELETE_ERROR: "Error al eliminar el usuario",
  EMPLOYEE_CREATE_ERROR: "Ha ocurrido un error al registrar el empleado",
  EMPLOYEE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el empleado",
  EMPLOYEE_DELETE_ERROR: "Error al eliminar el empleado",
  SCHEDULE_CREATE_ERROR: "Ha ocurrido un error al registrar el horario",
  SCHEDULE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el horario",
  SCHEDULE_DELETE_ERROR: "Error al eliminar el horario",
  VEHICLE_CREATE_ERROR: "Ha ocurrido un error al registrar el vehículo",
  VEHICLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el vehículo",
  VEHICLE_DELETE_ERROR: "Error al eliminar el vehículo",
  ROLE_CREATE_ERROR: "Ha ocurrido un error al registrar el rol",
  ROLE_UPDATE_ERROR: "Ha ocurrido un error al actualizar el rol",
  ROLE_DELETE_ERROR: "Error al eliminar el rol",
  USER_REGISTER_ERROR: "Error al registrar usuario",
  USER_REGISTER_ERROR_DETAIL: "Ha ocurrido un error al registrar el usuario",
  DATA_UPDATE_ERROR: "Ha ocurrido un error al actualizar los datos",
  PASSWORD_UPDATE_ERROR: "Ha ocurrido un error al actualizar la contraseña",
  ROLE_NOT_FOUND: "Rol no encontrado",
  RETRY_MESSAGE: "Intenta de nuevo",
  EMPLOYEE_CREATE_SUCCESS: "El registro del empleado fue exitoso",
  EMPLOYEE_UPDATE_SUCCESS: "La actualización del empleado fue exitosa",
  EMPLOYEE_DELETE_SUCCESS: "Empleado eliminado exitosamente",
  SCHEDULE_CREATE_SUCCESS: "El registro del horario fue exitoso",
  SCHEDULE_UPDATE_SUCCESS: "La actualización del horario fue exitosa",
  SCHEDULE_DELETE_SUCCESS: "Horario eliminado exitosamente",
  VEHICLE_CREATE_SUCCESS: "Vehículo creado exitosamente",
  VEHICLE_UPDATE_SUCCESS: "La actualización del vehículo fue exitosa",
  VEHICLE_DELETE_SUCCESS: "Vehículo eliminado exitosamente",
  COURIER_CREATE_SUCCESS: "Servicio de mensajería creado exitosamente",
  COURIER_UPDATE_SUCCESS: "La actualización del servicio fue exitosa",
  COURIER_DELETE_SUCCESS: "Servicio de mensajería eliminado exitosamente",
  COURIER_CREATE_ERROR: "Ha ocurrido un error al crear el servicio de mensajería",
  COURIER_UPDATE_ERROR: "Ha ocurrido un error al actualizar el servicio de mensajería",
  COURIER_DELETE_ERROR: "Ha ocurrido un error al eliminar el servicio de mensajería",
  ROLE_CREATE_SUCCESS: "Rol creado exitosamente",
  ROLE_UPDATE_SUCCESS: "La actualización del rol fue exitosa",
  ROLE_DELETE_SUCCESS: "Rol eliminado exitosamente",
  USER_CREATE_SUCCESS: "Usuario creado exitosamente",
  USER_UPDATE_SUCCESS: "La actualización del usuario fue exitosa",
  USER_ROLE_NOT_FOUND: "El rol seleccionado no existe",
  USER_STATUS_UPDATE_SUCCESS: "Estado del usuario actualizado exitosamente",
  USER_STATUS_UPDATE_ERROR: "Error al actualizar el estado del usuario",
  USER_PASSWORD_UPDATE_SUCCESS: "La contraseña fue actualizada exitosamente",
  USER_PASSWORD_UPDATE_ERROR: "Ha ocurrido un error al actualizar la contraseña",
};
export default NOTIFICATIONS; 