const PERMISSIONS = {
  CREATE_EMPLOYEES: "Crear Empleado",
  CREATE_ROLE: "Crear Rol",
  CREATE_SCHEDULES: "Crear Horario",
  CREATE_VEHICLES: "Crear Vehículo",
  DELETE_EMPLOYEES: "Eliminar Empleado",
  DELETE_ROLE: "Eliminar Rol",
  DELETE_SCHEDULES: "Eliminar Horario",
  DELETE_VEHICLES: "Eliminar Vehículo",
  EDIT_EMPLOYEE_ROLES: "Editar Roles de Empleados",
  EDIT_EMPLOYEES: "Editar Empleado",
  EDIT_ROLE: "Editar Rol",
  EDIT_SCHEDULES: "Editar Horario",
  EDIT_USER: "Editar Usuario",
  EDIT_VEHICLES: "Editar Vehículo",
  ENABLE_DISABLE_USER: "Habilitar/Deshabilitar Usuario",
  EXPORT_EXCEL_EMPLOYEES: "Exportar Excel de Empleados",
  EXPORT_EXCEL_ROLES: "Exportar Excel de Roles de Empleados",
  EXPORT_EXCEL_SCHEDULES: "Exportar Excel de Horarios",
  EXPORT_EXCEL_VEHICLES: "Exportar Excel de Vehículos",
  EXPORT_PDF_EMPLOYEES: "Exportar PDF de Empleados",
  EXPORT_PDF_ROLES: "Exportar PDF de Roles de Empleados",
  EXPORT_PDF_SCHEDULES: "Exportar PDF de Horarios",
  EXPORT_PDF_VEHICLES: "Exportar PDF de Vehículos",
  VIEW_ADMIN: "Ver Admin",
  VIEW_COURIER_SERVICE: "Ver Mensajería",
  VIEW_EMPLOYEE_ROLES_HOURS: "Ver Horas de Empleados",
  VIEW_EMPLOYEES: "Ver Empleados",
  VIEW_ROLES: "Ver Roles",
  VIEW_SCHEDULES: "Ver Horarios",
  VIEW_VEHICLES: "Ver Vehículos",
};
export default PERMISSIONS; 