const SELECTOR_TABLE = {
  PERIOD_WEEKLY: "Semanal",
  PERIOD_BIWEEKLY: "Quincenal",
  PERIOD_MONTHLY: "Mensual",
  WEEKLY: "Semanal",
  BIWEEKLY: "Quincenal",
  MONTHLY: "Mensual",
  WEEKS: "Semanas",
  WEEK: "Semana",
  BIWEEKS: "Quincenas",
  BIWEEK: "Quincena",
  EMPLOYEES: "Empleados",
  LOCATIONS: "Ubicaciones",
  SPECIAL_SCHEDULES: "Horarios Especiales",
  OTHER: "Otro",
  TOTAL_HOURS: "Horas totales",
  OVERTIME: "Horas extra",
  OVERTIME_HOURS: "Horas Extra",
  NO_EMPLOYEES: "No hay empleados para mostrar",
  ADJUST_TIME: "Ajustar tiempo",
  INFO: "Información",
  CLOSE: "Cerrar",
  ADJUST: "Ajustar",
  ADJUST_HOURS: "Ajuste de Horas",
  HOURS: "Horas",
  MINUTES: "Minutos",
  SEARCH_EMPLOYEE: "Buscar empleado...",
  SELECT_PERIOD: "Seleccionar periodo",
  TOOLTIP_INFO: "Ver información del empleado",
  TOOLTIP_ADJUST: "Ajustar horas trabajadas",
  WEEKLY_HOURS_MESSAGE: "Total de horas trabajadas en la semana:",
  BIWEEKLY_HOURS_MESSAGE: "Total de horas trabajadas en la quincena:",
  MONTHLY_HOURS_MESSAGE: "Total de horas trabajadas en el mes:",
  HOURS_TO_ADJUST: "Horas a ajustar",
  POSITIVE_NUMBER_REQUIRED: "Debe ser un número positivo",
  ADJUSTMENT_INFO: "Información de Ajuste",
  ADJUSTMENT_DESCRIPTION:
    "Ingresa la cantidad de horas a sumar o restar. Solo se permiten valores positivos.",
  CANCEL: "Cancelar",
  ADD: "Sumar",
  SUBTRACT: "Restar",
};
export default SELECTOR_TABLE;
