const TABLE_UI = {
  EDIT: "Editar",
  SAVE: "Guardar",
  CANCEL: "Cancelar",
  DELETE: "Eliminar",
  ACTIONS: "Acciones",
  NO_DATA: "No hay registros para mostrar",
  LOADING: "Cargando...",
  ROWS_PER_PAGE: "Filas por página",
  PAGE: "Página",
  OF: "de",
  PERMISSIONS_LABEL: "Permisos:",
  MORE: "+{n} más",
  SEARCH_PLACEHOLDER: "Buscar...",
  CONFIRM_DELETE_TITLE: "¿Eliminar registro?",
  CONFIRM_DELETE_TEXT:
    "¿Estás seguro de que deseas eliminar este registro? Esta acción no se puede deshacer.",
  CONFIRM_DELETE_ACCEPT: "Sí, eliminar",
  CONFIRM_DELETE_CANCEL: "Cancelar",
  TOOLTIP_EDIT: "Editar",
  TOOLTIP_DELETE: "Eliminar",
  TOOLTIP_SAVE: "Guardar cambios",
  TOOLTIP_CANCEL: "Cancelar edición",
  TOOLTIP_PASSWORD: "Cambiar contraseña",
  TOOLTIP_STATUS: "Activar/Desactivar",
  ENABLE: "Activar",
  DISABLE: "Desactivar",
  CHANGE_PASSWORD: "Cambiar contraseña",
  VIEW_MORE: "Ver más",
  VIEW_LESS: "Ver menos",
};
export default TABLE_UI;
